services:
  postgres:
    image: postgres:16
    container_name: giga-pg
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - pg_data:/var/lib/postgresql@16/data
    ports:
      - "5432:5432"

volumes:
  pg_data:
